# Generated by Django 2.2.5 on 2019-09-17 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import login.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('username', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=50)),
                ('primary_phone_no', models.CharField(max_length=10)),
                ('secondary_phone_no', models.CharField(max_length=10)),
                ('tg', models.BooleanField(default=False)),
                ('cc', models.BooleanField(default=False)),
                ('subjects', djongo.models.fields.ArrayModelField(model_container=login.models.Subjects)),
                ('labs', djongo.models.fields.ArrayModelField(model_container=login.models.Lab)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
