# Generated by Django 2.2.4 on 2019-08-08 16:46

from django.db import migrations, models
import djongo.models.fields
import login.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=50)),
                ('primary_phone_no', models.CharField(max_length=10)),
                ('secondary_phone_no', models.CharField(max_length=10)),
                ('tg', models.IntegerField(default=1, max_length=1)),
                ('cc', models.IntegerField(default=0, max_length=1)),
                ('subjects', djongo.models.fields.ArrayModelField(model_container=login.models.Subjects)),
                ('labs', djongo.models.fields.ArrayModelField(model_container=login.models.Lab)),
            ],
        ),
    ]
