# Generated by Django 2.2.5 on 2019-09-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='tg',
        ),
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.CharField(choices=[('F.E', 'F.E'), ('S.E', 'S.E'), ('T.E', 'T.E'), ('B.E', 'B.E')], default='T.E', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='division',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=2),
        ),
    ]
