# Generated by Django 2.2.5 on 2019-09-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190923_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='cc',
            field=models.CharField(choices=[('F.E', 'F.E'), ('S.E', 'S.E'), ('T.E', 'T.E'), ('B.E', 'B.E')], max_length=3),
        ),
    ]
