# Generated by Django 2.2.5 on 2019-09-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_lab_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='cc',
            field=models.CharField(choices=[('None', 'None'), ('F.E', 'F.E'), ('S.E', 'S.E'), ('T.E', 'T.E'), ('B.E', 'B.E')], default='None', max_length=3),
        ),
    ]
