# Generated by Django 2.2.5 on 2019-09-29 19:52

import attendance.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('lab', models.CharField(max_length=10)),
                ('batch', models.CharField(max_length=5)),
                ('attendance', djongo.models.fields.ArrayModelField(model_container=attendance.models.Attendance)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('subject', models.CharField(max_length=10)),
                ('div', models.CharField(max_length=5)),
                ('slots', models.IntegerField()),
                ('attendance', djongo.models.fields.ArrayModelField(model_container=attendance.models.Attendance)),
            ],
        ),
    ]
